#! /usr/bin/env bash
# Show tag statistics for each file given

echo 'scenarios implemented,mvp tag count,scenario count,feature name'
find . -iname \*.feature -print0 | while read -d $'\0' file
do
    echo -n 0,
    grep -h -c '^ *@mvp' "$file" | tr -d \\012
    echo -n ,
    grep -h -c '^ *Scenario' "$file" | tr -d \\012
    echo ,"${file%%.feature}"
done
