#! /usr/bin/env bash
# make sure tags used in all the feature files in or under the current directory
# in use are present in the given tags.md, as definitive source.

if (( $# != 1 )); then
    echo Usage: $0 name-of-tags.md-file
    exit -1
fi
tags_file="$1"


if [ -r $tags_file ]; then
    ok_tags=($(sed -e '1,/^---/d' -e 's/  *|.*//' -e 's/^/@/' $tags_file ))
    echo OK Tags: "${ok_tags[@]}"
else
    echo $0 Cannot read tags file $tags_file
    exit 1
fi

find . -iname \*.feature -print0 | while read -d $'\0' file
do
    file_tags=($(grep '^ *@' "$file" | tr ' ' \\012 | sort -u ))
    #echo file "$file" tags: ${file_tags[@]}
    for one_tag in "${file_tags[@]}"
    do
        if [[ ! " ${ok_tags[@]} " =~ " ${one_tag} " ]]; then
            echo "Bad tag:" $one_tag in $file
        fi
    done
done
